### PR TITLE
Added support for the rdp-database and modified the test to use the f…

### PR DESCRIPTION
**Pull request by emnilsson**
…ormat_taxonomy-module

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
 - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
 - [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — COMMENTED** [review]
I note that Unite still has @jtangrot 's script and that we after I added mine hence have two for the same purpose. I also note that her script expects some ranks to be preceded by "D_n__" where n is a number; I don't see any such in the file I've downloaded, nor in the other version of the fungi file. We know that her script works though.

I also noted today that there are multiple Unite databases, two each for fungi and all eukaryotes respectively. I'm not sure what the difference between two for fungi and two for all eukaryotes is -- except that one is twice the size of the other -- so I've asked Anna to prioritize; she passed it on to Jeanette. In addition, there are dates corresponding to releases (i.e. 8.0, 8.2 etc.), so our URLs will have to be updated regularly, probably quite often.

**Comment by emnilsson** [comment]
> I note that Unite still has @jtangrot 's script and that we after I added mine hence have two for the same purpose. I also note that her script expects some ranks to be preceded by "D_n__" where n is a number; I don't see any such in the file I've downloaded, nor in the other version of the fungi file. We know that her script works though.
> 

There's quite a lot of "residues" (e.g. links to databases etc are wrong), but I'm looking at that now. I accidentally pushed my previous changes to nf-core/ampliseq DSL2 instead of to my fork, this PR is mostly to make sure that the tests work.

> I also noted today that there are multiple Unite databases, two each for fungi and all eukaryotes respectively. I'm not sure what the difference between two for fungi and two for all eukaryotes is -- except that one is twice the size of the other -- so I've asked Anna to prioritize; she passed it on to Jeanette. In addition, there are dates corresponding to releases (i.e. 8.0, 8.2 etc.), so our URLs will have to be updated regularly, probably quite often.

Is that true for the general fasta as well?

**Comment by erikrikarddaniel** [comment]
Den tis 23 mars 2021 kl 15:11 skrev emnilsson ***@***.***>:
>
> I note that Unite still has @jtangrot 's script and that we after I added mine hence have two for the same purpose. I also note that her script expects some ranks to be preceded by "D_n__" where n is a number; I don't see any such in the file I've downloaded, nor in the other version of the fungi file. We know that her script works though.
>
> There's quite a lot of "residues" (e.g. links to databases etc are wrong), but I'm looking at that now. I accidentally pushed my previous changes to nf-core/ampliseq DSL2 instead of to my fork, this PR is mostly to make sure that the tests work.
>
OK. (I saw the thread on Slack...)

> I also noted today that there are multiple Unite databases, two each for fungi and all eukaryotes respectively. I'm not sure what the difference between two for fungi and two for all eukaryotes is -- except that one is twice the size of the other -- so I've asked Anna to prioritize; she passed it on to Jeanette. In addition, there are dates corresponding to releases (i.e. 8.0, 8.2 etc.), so our URLs will have to be updated regularly, probably quite often.
>
> Is that true for the general fasta as well?
>
I haven't seen anything looking like a "general fasta". I see four
fasta files per version, none of them having, AFAIK, stable urls
between versions. It would be great with a "latest" here too...

**Comment by emnilsson** [comment]
> I haven't seen anything looking like a "general fasta". I see four fasta files per version, none of them having, AFAIK, stable urls between versions. It would be great with a "latest" here too...

But aren't they updated very irregularly? At least the two newer versions - last one was in April 2020 and the one before that in November 2018. To me that wouldn't qualify as often..

**Comment by erikrikarddaniel** [comment]
Den tis 23 mars 2021 kl 15:36 skrev emnilsson ***@***.***>:
>
> I haven't seen anything looking like a "general fasta". I see four fasta files per version, none of them having, AFAIK, stable urls between versions. It would be great with a "latest" here too...
>
> But aren't they updated very irregularly? At least the two newer versions - last one was in April 2020 and the one before that in November 2018. To me that wouldn't qualify as often..
>
You're right, maybe not too bad.

**Comment by jtangrot** [comment]
> I note that Unite still has @jtangrot 's script and that we after I added mine hence have two for the same purpose. I also note that her script expects some ranks to be preceded by "D_n__" where n is a number; I don't see any such in the file I've downloaded, nor in the other version of the fungi file. We know that her script works though.

My script should not expect ranks to be preceded by D_n_, instead that's (in my understanding) what qiime expects as input, and what the taxonomies are converted to in the script. However, the script does expect the ranks to be preceeded by k__, p__, etc., which is the case for the UNITE file named UNITE_public_xx.xx.xxxx.fasta. This file contains "all" fungal ITS sequences of UNITE and INSDC. The UNITE "general FASTA release" in files named sh_general_release_dynamic_xxxxx.fasta, containing representative sequences for all SHs, present the taxonomies in the same way, and it should be possible to support both of these files/databases without any extra work.

**Comment by d4straub** [comment]
As far as I understood QIIME2 doesn't really care about any additions such as  `D_n_` or `k__, p__, etc.` in taxa names.

**Comment by erikrikarddaniel** [comment]
Den ons 24 mars 2021 kl 13:47 skrev Daniel Straub ***@***.***>:
>
> As far as I understood QIIME2 doesn't really care about any additions such as D_n_ or k__, p__, etc. in taxa names.
>
This was probably just my misunderstanding of Jeanette's code. And
since we're more or less dropping support for QIIME2 taxonomy
assignment it probably doesn't matter.

/D

**Pull request merged**
