### PR TITLE
Update unite to version 9.0

### PR DESCRIPTION
**Pull request by jtangrot**
UNITE databases are updated to version 9.0, and for qiime version 8.3 is also added. However, I cannot make unite-fungi 9.0 work with qiime (unite-alleuk 9.0 works fine), so I skipped that one for now in the interest of having updated UNITE databases for assignTaxonomy and sintax.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jtangrot** [comment]
This PR addresses issue #574

**Comment by jtangrot** [comment]
> > However, I cannot make unite-fungi 9.0 work with qiime (unite-alleuk 9.0 works fine), so I skipped that one for now in the interest of having updated UNITE databases for assignTaxonomy and sintax.
> 
> agreed _edit: actually, why not add unite-fungi 9.0 for QIIME as well but skip sh files (if thats the problem)_
> 

No, the sh files are not the problem, those are only used together with / after assignTaxonomy. It's the qiime formatted database that misbehaves in some way ("this classifier does not support confidence values"), or I am doing something wrong. Also see comment in issue 574.

> >I could either specify unite-fungi=8.3 in the test config, or instead try to increase max_memory in the config file. Which option is preferred?
>
> better use unite-fungi=8.3, we do not want to mess with nf-core max resource settings, might lead to more problems.

OK, thanks!

**Review by d4straub — APPROVED** [review]
Looks good to me!

**Comment by jtangrot** [comment]
Thanks!

**Pull request merged**
