### PR TITLE
PR for release 1.1.1

### PR DESCRIPTION
**Pull request by apeltzer**
Update to latest QIIME2 2019/10 release. Some bugfixes, Github Actions etc pp. 

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/ampliseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/ampliseq)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Should be fine now - your and another review required now, then this is good for a release I think 👍

**Comment by apeltzer** [comment]
Hm, no this seems to work for me in the browser? 

https://github.com/nf-core/ampliseq/blob/master/docs/usage.md

**Comment by d4straub** [comment]
And in dev branch?
https://github.com/nf-core/ampliseq/blob/dev/docs/usage.md

**Comment by apeltzer** [comment]
Checking what went wrong there...

**Comment by d4straub** [comment]
Oh while you are at it, why not immediately also put #99 in there :P

**Pull request merged**
