### PR TITLE
Add sbdi-gtdb R09-RS220

### PR DESCRIPTION
**Pull request by erikrikarddaniel**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

The latest release of Sativa vetted GTDB added.

### CODE REVIEW

**Comment by d4straub** [comment]
Uff, failing tests are 
`Can't stage file [https://files.plutof.ut.ee](https://files.plutof.ut.ee/ `...
related to https://github.com/nf-core/ampliseq/issues/764. We'll need to fix that asap :D

**Review by d4straub — APPROVED** [review]
LGTM!

**Comment by erikrikarddaniel** [comment]
> Uff, failing tests are `Can't stage file [https://files.plutof.ut.ee](https://files.plutof.ut.ee/ `... related to #764. We'll need to fix that asap :D

Easiest is perhaps to comment out that test for the moment? I can do that in this PR if you want to, then try to find urls for the files in another PR.

**Comment by d4straub** [comment]
Easiest would be if I bypass tests and just merge it. The fix for the links could come in a follow-up PR. Is that ok with you?

**Comment by erikrikarddaniel** [comment]
> Easiest would be if I bypass tests and just merge it. The fix for the links could come in a follow-up PR. Is that ok with you?

Go ahead!

**Pull request merged**
