### PR TITLE
Update version to 2.6.0dev

### PR DESCRIPTION
**Pull request by d4straub**
After release update of version number & CHANGELOG

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
Fantastic!

**Comment by d4straub** [comment]
> Fantastic!

Thanks!

> (Except maybe for the two failing tests...)
```
Caused by:
  Can't stage file https://data.qiime2.org/2022.11/tutorials/training-feature-classifiers/85_otus.fasta -- reason: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```
Yes, very annoying, it seems like QIIME2 website's certificate expired...

**Comment by d4straub** [comment]
I'd say we give it a few days but if that isnt changing we have to abandon data.qiime2.org
There is an issue already in https://forum.qiime2.org/t/ssl-certificate-for-qiime2-2022-11-outdated/25660

**Comment by erikrikarddaniel** [comment]
Is this only for data files like taxonomies, or for the binaries too?
A hack would perhaps be to disable qiime in tests for the time being?

**Comment by d4straub** [comment]
> Is this only for data files like taxonomies, or for the binaries too?

Only taxonomies are hosted at data.qiime2.org, the docker container is at quay.io as all other docker containers as well.

> A hack would perhaps be to disable qiime in tests for the time being?

Yes that would work. I'll disable it in the beginning of next week if it doesn't improve til then.

**Comment by d4straub** [comment]
Problem resolved!

**Pull request merged**
