### PR TITLE
Add attribution to workflow design

### PR DESCRIPTION
**Pull request by jfy133**
The CC-BY license requires attribution to the original author, so I've added the original author back to the workflow diagram, but saying it's 'based on'.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](<https://github.com/>nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by d4straub** [comment]
While I appreciate the proposed change (attribution to the original author), your PR also changes font style and size and therefore all element alignments are messed up in the png. Do you want to revert all changes except the attribution to the original author or I can attempt to fix that myself?

**Review by d4straub — CHANGES_REQUESTED** [review]
revert font style changes

**Comment by jfy133** [comment]
Oops, sorry about that! I think best in this case you revert, and you can just add the attribution manually.

**Comment by jfy133** [comment]
@d4straub I've reverted but I think there is somethign with the SVG and inkscape which it keeps changing stuff automatically

I suggest that you add the attribution (below) yourself in your own PR

image

**Pull request closed without merging**
