### PR TITLE
Merging template updates 2.12

### PR DESCRIPTION
**Pull request by d4straub**
Template update 2.12

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
You're quick! :-)

**Comment by d4straub** [comment]
Thanks, but somehow I cannot get nf-core tools/linting locally to work and I need to correct those failing tests ;)

**Comment by d4straub** [comment]
Only remaining issue is 
```
 ╭─ [✗] 1 Subworkflow Test Failed ──────────────────────────────────────────────╮
│                           ╷                        ╷                         │
│ Subworkflow name          │ File path              │ Test message            │
│╶──────────────────────────┼────────────────────────┼────────────────────────╴│
│ fasta_newick_epang_gappa  │ subworkflows/nf-core/… │ Local copy of           │
│                           │                        │ subworkflow does not    │
│                           │                        │ match remote            │
│                           ╵                        ╵                         │
╰──────────────────────────────────────────────────────────────────────────────╯
```
I am a little surprised that this is an issue, will see what I can do about it.

**Comment by d4straub** [comment]
For posterity: updating subworkflow `fasta_newick_epang_gappa` was tricky because module `mafft` was changed and the most recent version isnt compatible with the subworkflow:

> Process `NFCORE_AMPLISEQ:AMPLISEQ:FASTA_NEWICK_EPANG_GAPPA:MAFFT` declares 6 input channels but 2 were specified

Therefore I fixed the `mafft` module at version `feb29be775d9e41750180539e9a3bdce801d0609` in `.nf-core.yml`. That must be removed again in case the module should be updated to another version.

**Pull request merged**
