### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by d4straub**
## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/ampliseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/ampliseq)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Should I review and we release this with the centralized configs fix?

**Comment by d4straub** [comment]
I am going to add a test run for multiple sequencing runs.
To do:
- add folder with sequences and metadata file to nf-core/test-datasets branch ampliseq
- add ampliseq/conf/test-multi.config
- add additional test command to ampliseq/.travis.yml

**Comment by apeltzer** [comment]
Aah, that should go to the https://github.com/nf-core/test-datasets repository and then be referenced in a separate test_multi profile!

Hlatyping does something similar:

https://github.com/nf-core/test-datasets/pulls

https://github.com/nf-core/hlatyping/tree/master/conf

**Comment by d4straub** [comment]
I also have a precedence for my lazy version using wget to download files: 
https://github.com/nf-core/rnafusion/blob/master/.travis.yml (bottom)

I thought this actually helps in case of ampliseq to test also the more complicated multiple sequencing run file import and does not require a convoluted new import function just for this test.

At least the metadata sheet will go to https://github.com/nf-core/test-datasets, sure, atm its in my fork and i just would like to test whether it works like that :)

**Comment by d4straub** [comment]
Well, it works in general, I adjusted the metadata file and it should be good.
I'll have a look if I can somehow improve it that its more in line with the nf-core idea.

**Comment by d4straub** [comment]
Even if it would go through, I would still have to update nf-core/test-datasets and test_multi.conf. Currently it uses my fork d4straub/test-datasets for data

**Comment by d4straub** [comment]
Cant get "second version of test_multi" it to work: 

```
Mar-08 13:24:26.859 [Actor Thread 6] ERROR nextflow.processor.TaskProcessor - Error executing process > 'trimming_multi (run1-1_S103)'

Caused by:
  java.lang.NullPointerException

java.lang.NullPointerException: null
	at java.nio.file.Files.provider(Files.java:97)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at nextflow.util.CacheHelper.hashFile(CacheHelper.java:203)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:158)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:150)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:90)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:86)
	at nextflow.util.CacheHelper$hasher.call(Unknown Source)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:1836)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:535)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Cant figure out whats wrong. All files are accessible, all channels prior that process seem properly filled, the only source of the error seems to me that particular process. Also the script commands look ok. The process itself works with data when not using -profile test_multi.
It appears to me that working directories (work/xy/...) are created but completely empty. I cant trace the source of that error.

**Comment by apeltzer** [comment]
Any updates on this Daniel?

**Comment by apeltzer** [comment]
Lets see! Template V1.6 changes have been merged, i probably should test locally as well ...

**Comment by apeltzer** [comment]
I suspect its something with the `extract_folders`stuff that isn't working properly. Maybe try simulating this and debugging it using `nextflow console` ?

**Comment by d4straub** [comment]
@apeltzer I implemented all I planned for 1.1.0, requesting review

**Comment by apeltzer** [comment]
```
Caused by:
  Process `output_documentation (1)` terminated with an error exit status (127)
Command executed:
  markdown_to_html.r output.md results_description.html
Command exit status:
  127
Command output:
  (empty)
Command error:
  /opt/conda/envs/nf-core-ampliseq-1.0.0/lib/R/bin/exec/R: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory

```

Probably need to pin `ncurses` I fear @d4straub

**Comment by d4straub** [comment]
@apeltzer This is a Travis CI specific problem, isnt it? I cant recall encountering that problem on any clusters or locally and earlier also Travis tests run past that point (but failed in linting usually...).

An idea: is the container re-build for the dev branch even so the container of dev is identical to manster? Because re-building might be problematic due to also failing to build the conda environment. Something must have changed with the conda packages again.

**Pull request merged**
