### PR TITLE
update nf-core modules and local picrust module

### PR DESCRIPTION
**Pull request by d4straub**
Update software version as in https://github.com/nf-core/ampliseq/pull/468 but not QIIME2 (newer containers fail to run with docker).

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
Looks fine.

**Comment by d4straub** [comment]
Hm, there are multiple warnings such as:
>  WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

**Comment by erikrikarddaniel** [comment]
> Hm, there are multiple warnings such as:
> 
> > WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition

I think I saw that once yesterday. Sounds like something changed in Nextflow. Looks a bit ugly for users perhaps?

**Comment by d4straub** [comment]
First PR that contains a warning with `test_pacbio_its` seems https://github.com/nf-core/ampliseq/pull/476,  and https://github.com/nf-core/ampliseq/pull/477 contains even two. Will fix that in a separate PR.

**Pull request merged**
