### PR TITLE
prepend X to sample IDs that start with a number

### PR DESCRIPTION
**Pull request by d4straub**
Closes https://github.com/nf-core/ampliseq/issues/357

I implemented the first proposed solution, but conditional on `--metadata`: When encountering a sample ID that starts with a number the pipeline stops with a descriptive error, but only when metdata is given.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
LGTM.

**Comment by d4straub** [comment]
Thanks, but I think I only solved this for the samplesheet input but not for direct fastq file input. Also there sample IDs should be prepended by an X when having a number at the first place. Will do this asap.

**Comment by d4straub** [comment]
Now all sampleIDs derived from samplesheet or direct fastq input will be prepended with an X when starting with a number.

However, after some further test, it appears that this problem is not solved as simple as anticipated. While the sampleIDs are now consistent in the pipeline, the metadata still doesnt match sampleIDs, because it is not modified. Essentially, there would need to be one more process that opens, modifies the metadata ( and potentially verifies the metadata against the sampleIDs from samplesheet/files).
I am going to attempt that soon-ish.

**Comment by erikrikarddaniel** [comment]
I noticed yesterday that you updated the documentation so it actually forbids sample names starting with numbers. Instead of trying to fix sample names, the pipeline could fail with a request to update sample names, stressing that this needs to be done for filenames, input.tsv and metadata. Seems easier.

**Comment by d4straub** [comment]
Ok, I think I'll just throw an error than. But I prefer to only do this in case there is metadata specified. I do not want to burden the user in case there is no metadata, if possible, because the pipeline will succeed in that case regardless of sample IDs.

**Review by erikrikarddaniel — APPROVED** [review]
I agree about letting it pass if there's no metadata, so LGTM.

**Comment by d4straub** [comment]
Ok, lets see how it goes and whether there are complains. After all, it would be easy to change again.

**Pull request merged**
